<?php

/**
 * Implements hook_install().
 */
function clicode_install() {
  drupal_set_message(t('You need to do some '.l('config', 'admin/config/media/clicode').' for clicode module.'));
}

/**
 * Implements hook_uninstall().
 */
function clicode_uninstall() {
  variable_del('clicode_server_url');
  variable_del('clicode_server_port');
  variable_del('clicode_iframe_width');
  variable_del('clicode_iframe_height');
}